on:
  workflow_call:
    inputs:
      LANGUAGE:
        required: false
        type: string
        default: "java"
      CODEQL_ENABLED:
        required: false
        type: boolean
        default: true
      TEAM:
        required: false
        type: string
        default: "teamdigihot"
      JAVA_DISTRIBUTION:
        required: false
        type: string
        default: "temurin"
      JAVA_VERSION:
        required: false
        type: string
        default: "17"
      NODE_VERSION:
        required: false
        type: string
        default: "16"
      BUILD_CACHE:
        required: false
        type: string
        default: "gradle"
      NAIS_RESOURCE:
        required: false
        type: string
        default: "naiserator.yml"
      NAIS_VARS:
        required: false
        type: string
        default: "naiserator-dev.json"
      CLUSTER:
        required: false
        type: string
        default: "dev-gcp"
      WORKING_DIRECTORY:
        required: false
        type: string
        default: "./"
      IMAGE_SUFFIX:
        required: false
        type: string
    secrets:
      NAIS_DEPLOY_APIKEY:
        required: true
      OPTIONAL_SECRET:
        required: false
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true
      CODEQL_EXTERNAL_REPO_TOKEN:
        required: false
    outputs:
      image:
        description: "Image from nais build push action"
        value: ${{ jobs.deploy-dev.outputs.image }}
jobs:
  deploy-dev:
    permissions:
      contents: write
      id-token: write
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    environment: ${{ inputs.CLUSTER }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
      - name: Setup CodeQL
        if: ${{ inputs.CODEQL_ENABLED }}
        uses: github/codeql-action/init@v2
        with:
          external-repository-token: ${{ secrets.GITHUB_TOKEN }}
          languages: ${{ (inputs.LANGUAGE == 'node' && 'javascript') || inputs.LANGUAGE }}
      - name: Setup java
        if: ${{ inputs.LANGUAGE == 'java' }}
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}
          cache: ${{ inputs.BUILD_CACHE }}
      - name: Setup Node
        if: ${{ inputs.LANGUAGE == 'node' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: ${{ inputs.BUILD_CACHE }}

      - name: Validate Gradle wrapper
        if: ${{ inputs.BUILD_CACHE == 'gradle' }}
        uses: gradle/wrapper-validation-action@v1

      - name: Build gradle and upload dependency graph
        if: ${{ inputs.BUILD_CACHE == 'gradle' }}
        uses: gradle/gradle-build-action@v2.7.0
        env: # Eksluder test dependencies
          DEPENDENCY_GRAPH_INCLUDE_CONFIGURATIONS: compileClasspath|runtimeClasspath
        with:
          dependency-graph: generate-and-submit
          arguments: build

      - name: Perform CodeQL Analysis
        if: ${{ inputs.CODEQL_ENABLED }}
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{ (inputs.LANGUAGE == 'node' && 'javascript') || inputs.LANGUAGE }}"

      - name: Pre-deploy
        uses: navikt/digihot-deploy/actions/pre-deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: docker-build-push
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ${{ inputs.TEAM }}
          tag: ${{ env.VERSION_TAG }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          dockerfile: "${{ inputs.WORKING_DIRECTORY }}Dockerfile"
          image_suffix: ${{ inputs.IMAGE_SUFFIX }}
          build_secrets: |
            "optional_secret=${{ secrets.OPTIONAL_SECRET }}"

      - name: Deploy to ${{ inputs.CLUSTER }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ inputs.CLUSTER }}
          RESOURCE: ${{ inputs.NAIS_RESOURCE }}
          VARS: ${{ inputs.NAIS_VARS }}

      - name: Post-deploy
        uses: navikt/digihot-deploy/actions/post-deploy@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Draft release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.VERSION_TAG }}
          name: ${{ env.DRAFT_NAME }}
          body: ${{ env.CHANGE_LOG }}
          draft: true
          prerelease: false
